<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-12-10 05:21
=======
<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-12-10 04:42
=======
# Generated by Django 3.2.8 on 2021-12-09 07:39
>>>>>>> b94a82a739d6f59db35c2decdfad23db1b1f1d5d
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('day_time', models.DateTimeField()),
                ('patient_id', models.CharField(max_length=9)),
                ('appointment_type', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'appointment',
=======
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'appointment_type',
            },
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('doctor_email', models.EmailField(max_length=100)),
                ('doctor_phone', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'db_table': 'doctor',
>>>>>>> b94a82a739d6f59db35c2decdfad23db1b1f1d5d
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
=======
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
<<<<<<< HEAD
>>>>>>> main
                ('byu_id', models.CharField(max_length=9)),
=======
                ('byu_id', models.CharField(blank=True, max_length=9)),
                ('password', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=100)),
                ('patient_phone', models.CharField(blank=True, max_length=13)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.DateTimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.patient')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reservation.appointment_type')),
>>>>>>> b94a82a739d6f59db35c2decdfad23db1b1f1d5d
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
